# -----------------------------
# TAB MANAGEMENT
# -----------------------------

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled
tab_activity_symbol "+ "
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

# New tab
map ctrl+shift+t new_tab

# Close current tab
map ctrl+shift+w close_tab

# Next/Previous tab
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# Go directly to tab number
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

# Rename tab
map ctrl+shift+r set_tab_title

# Move tabs
map ctrl+shift+left move_tab_backward
map ctrl+shift+right move_tab_forward

# New OS window
map ctrl+shift+n new_os_window

# Split panes
map ctrl+shift+enter launch --location=vsplit
map ctrl+shift+d launch --location=hsplit

# Navigate panes
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# FONTS
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11.5
disable_ligatures always

# CURSOR
cursor #cccccc
cursor_shape block
cursor_blink_interval 0
cursor_trail 200
cursor_trail_color green
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

shell_integration no-cursor

# SCROLL
scrollback_lines 100000
wheel_scroll_multiplier 5.0


